#!/bin/bash

set -x

set -eo pipefail

# Run the original assemble script. This will ensure that everything is
# copied into place and setup.

/usr/libexec/s2i/assemble

# Tar up a copy of the original wp-content directory so we can restore
# it when the Wordpress image is started up the first time and the
# wp-content directory has been replaced with a persistent volume.

tar cvf wp-content.tar wp-content

# Edit the wp-config-sample.php to allow plugins and themes to be
# installed directly into file system.

sed -i "/'DB_COLLATE', *'');/a\
define('FS_METHOD', 'direct');" wp-config-sample.php

# Edit the wp-config-sample.php to force use of a secure connection
# for login and adminstration.

sed -i "/'DB_COLLATE', *'');/a\
define( 'FORCE_SSL_ADMIN', true );" wp-config-sample.php

# Edit the wp-config-sample.php to ensure that static files are served
# up over same protocol as request to avoid mixed content errors.

sed -i "/'DB_COLLATE', *'');/a\
if (strpos(\$_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) \$_SERVER['HTTPS']='on';" wp-config-sample.php
