#!/bin/bash

set -x

set -eo pipefail

# Run the original assemble script. This will ensure that everything is
# copied into place and setup.

/usr/libexec/s2i/assemble

# Tar up a copy of the original wp-content directory so we can restore
# it when the Wordpress image is started up the first time and the
# wp-content directory has been replaced with a persistent volume.

tar cvf wp-content.tar wp-content

# Edit the wp-config-sample.php to add additional options so that plugins
# and themes can be installed into file system directly. Also ensure that
# use a secure connection for login and adminstration.

sed -i "/'DB_COLLATE', '');/a\
define('FS_METHOD', 'direct');" wp-config-sample.php

sed -i "/'DB_COLLATE', '');/a\
define( 'FORCE_SSL_ADMIN', true );" wp-config-sample.php
