#!/bin/bash

set -x

set -eo pipefail

# Check the wp-content directory and if the plugins and themes directories
# do not exist, restore the contents of the directory from the tarball we
# created in the assemble script.

if [ ! -d wp-content/plugins -a ! -d wp-content/themes ]; then
    tar xvf wp-content.tar
fi

# Check whether the wp-config.php file has been generated previously. If
# not then we need to generate it. This is placed in the wp-content directory
# on basis that it is in persistent storage.

secret() {
    python -c 'import random; import string; print("".join([random.SystemRandom().choice(string.ascii_letters+string.digits) for i in range(50)]))'
}

if [ ! -f wp-config.php -a ! -f wp-content/wp-config.php ]; then
    cp wp-config-sample.php wp-content/wp-config-temp.php

    sed -i "s/'DB_NAME', *'database_name_here'/'DB_NAME', '$MYSQL_DATABASE'/" wp-content/wp-config-temp.php
    sed -i "s/'DB_USER', *'username_here'/'DB_USER', '$MYSQL_USER'/" wp-content/wp-config-temp.php
    sed -i "s/'DB_PASSWORD', *'password_here'/'DB_PASSWORD', '$MYSQL_PASSWORD'/" wp-content/wp-config-temp.php
    sed -i "s/'DB_HOST', *'localhost'/'DB_HOST', '$MYSQL_HOST'/" wp-content/wp-config-temp.php
    sed -i "s/\$table_prefix *= *'wp_';/\$table_prefix = '$MYSQL_TABLE_PREFIX';/" wp-content/wp-config-temp.php

    sed -i "s/'AUTH_KEY', *'put your unique phrase here'/'AUTH_KEY', '`secret`'/" wp-content/wp-config-temp.php
    sed -i "s/'SECURE_AUTH_KEY', *'put your unique phrase here'/'SECURE_AUTH_KEY', '`secret`'/" wp-content/wp-config-temp.php
    sed -i "s/'LOGGED_IN_KEY', *'put your unique phrase here'/'LOGGED_IN_KEY', '`secret`'/" wp-content/wp-config-temp.php
    sed -i "s/'NONCE_KEY', *'put your unique phrase here'/'NONCE_KEY', '`secret`'/" wp-content/wp-config-temp.php
    sed -i "s/'AUTH_SALT', *'put your unique phrase here'/'AUTH_SALT', '`secret`'/" wp-content/wp-config-temp.php
    sed -i "s/'SECURE_AUTH_SALT', *'put your unique phrase here'/'SECURE_AUTH_SALT', '`secret`'/" wp-content/wp-config-temp.php
    sed -i "s/'LOGGED_IN_SALT', *'put your unique phrase here'/'LOGGED_IN_SALT', '`secret`'/" wp-content/wp-config-temp.php
    sed -i "s/'NONCE_SALT', *'put your unique phrase here'/'NONCE_SALT', '`secret`'/" wp-content/wp-config-temp.php

    mv wp-content/wp-config-temp.php wp-content/wp-config.php
fi

# Copy the previously generated wp-config.php from the wp-content diretcory
# into location Wordpress is expecting it.

cp wp-content/wp-config.php wp-config.php

# Execute the original run script, replacing this script as process ID 1.

exec /usr/libexec/s2i/run
