#!/bin/bash

set -x

set -eo pipefail

# Ensure the wp-content directory exists in the persistent volume.

mkdir -p /opt/app-root/data/wp-content

# Check the wp-content directory and if the plugins and themes directories
# do not exist, restore the contents of the directory from the tarball we
# created in the assemble script.

if [ ! -d wp-content/plugins -a ! -d wp-content/themes ]; then
    tar -C wp-content -xvf /opt/app-root/wp-content.tar
fi

# Check whether the wp-config.php file has been generated previously. If
# not then we need to generate it. This is placed in the persistent volume.

secret() {
    python -c 'import random; import string; print("".join([random.SystemRandom().choice(string.ascii_letters+string.digits) for i in range(50)]))'
}

if [ ! -f /opt/app-root/data/wp-config.php ]; then
    TMPCONFIG=/opt/app-root/data/wp-config-temp.php
    cp wp-config-sample.php $TMPCONFIG

    sed -i "s/'DB_NAME', *'database_name_here'/'DB_NAME', '$MYSQL_DATABASE'/" $TMPCONFIG
    sed -i "s/'DB_USER', *'username_here'/'DB_USER', '$MYSQL_USER'/" $TMPCONFIG
    sed -i "s/'DB_PASSWORD', *'password_here'/'DB_PASSWORD', '$MYSQL_PASSWORD'/" $TMPCONFIG
    sed -i "s/'DB_HOST', *'localhost'/'DB_HOST', '$MYSQL_HOST'/" $TMPCONFIG
    sed -i "s/\$table_prefix *= *'wp_';/\$table_prefix = '$MYSQL_TABLE_PREFIX';/" $TMPCONFIG

    sed -i "s/'AUTH_KEY', *'put your unique phrase here'/'AUTH_KEY', '`secret`'/" $TMPCONFIG
    sed -i "s/'SECURE_AUTH_KEY', *'put your unique phrase here'/'SECURE_AUTH_KEY', '`secret`'/" $TMPCONFIG
    sed -i "s/'LOGGED_IN_KEY', *'put your unique phrase here'/'LOGGED_IN_KEY', '`secret`'/" $TMPCONFIG
    sed -i "s/'NONCE_KEY', *'put your unique phrase here'/'NONCE_KEY', '`secret`'/" $TMPCONFIG
    sed -i "s/'AUTH_SALT', *'put your unique phrase here'/'AUTH_SALT', '`secret`'/" $TMPCONFIG
    sed -i "s/'SECURE_AUTH_SALT', *'put your unique phrase here'/'SECURE_AUTH_SALT', '`secret`'/" $TMPCONFIG
    sed -i "s/'LOGGED_IN_SALT', *'put your unique phrase here'/'LOGGED_IN_SALT', '`secret`'/" $TMPCONFIG
    sed -i "s/'NONCE_SALT', *'put your unique phrase here'/'NONCE_SALT', '`secret`'/" $TMPCONFIG

    mv $TMPCONFIG /opt/app-root/data/wp-config.php
fi

# Link the previously generated wp-config.php from the persistent volume
# into location WordPress is expecting it.

ln -s /opt/app-root/data/wp-config.php wp-config.php

# Check whether the .htaccess file has been generated previously. If not
# then we need to generate it. This is placed in the persistent volume.

if [ ! -f /opt/app-root/data/.htaccess ]; then
    cat > /opt/app-root/data/.htaccess << !
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
!
fi

# Link the previously generated .htaccess from the persistent volume
# into location WordPress is expecting it.

ln -s /opt/app-root/data/.htaccess .htaccess

# Execute the original run script, replacing this script as current process.

exec /usr/libexec/s2i/run
